[book]
authors = ["Yusef Karim"]
language = "en"
src = "src"
title = "Ottawa RISC-V"
description = "Ottawa RISC-V embedded systems training (VEGA edition)"

[rust]
edition = "2024"

[output.html]
default-theme = "Ayu"
preferred-dark-theme = "Ayu"
mathjax-support = true
# no-section-label = true

[build]
create-missing = false
